### ISSUE TITLE
mathcomp for coq-8.9

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/docker-mathcomp#1]
Hi @erikmd I thought you said somewhere there was a reason for not having a docker build for mathcomp on coq 8.9, could you remind me what it is?

**Comment by erikmd** [comment]
Hi @CohenCyril, the only missing ingredient is an opam release for bignums (coq/bignums#17).
There is now a pending PR coq/opam-coq-archive#568, so as soon as it is merged I'll publish the corresponding image in [coqorg/coq](https://hub.docker.com/r/coqorg/coq/tags) then in [mathcomp/mathcomp](https://hub.docker.com/r/mathcomp/mathcomp/tags).

**Comment by erikmd** [comment]
done: `docker run --rm -it mathcomp/mathcomp:1.7.0-coq-8.9 rlwrap coqtop`
